feat: Device autoupdate test and device service (#29)
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Co-authored-by: flxdot <flxdot@users.noreply.github.com>

diff --git a/.github/workflows/test-lib-py_edge_interface.yml b/.github/workflows/test-lib-py_edge_interface.yml
--- a/.github/workflows/test-lib-py_edge_interface.yml
+++ b/.github/workflows/test-lib-py_edge_interface.yml
@@ -147,3 +147,20 @@ jobs:
         message: "update lib/py_edge_interface"
         coauthor_email: ${{ github.event.pull_request.user.login }}@users.noreply.github.com
         coauthor_name: ${{ github.event.pull_request.user.login }}
+
+    - name: Set up - Get changed files for CHANGELOG.md
+      if: ${{ !cancelled() }}
+      id: detect-changed-files
+      uses: tj-actions/changed-files@v42
+      with:
+        files_yaml: |
+          pyproject_toml:
+            - lib/py_edge_interface/pyproject.toml
+          python_files:
+            - lib/py_edge_interface/carlos/**/*.py
+    - name: Test - Version bump
+      # This step will fail if there are python files changed but the version in pyproject.toml is not updated
+      if: (steps.detect-changed-files.outputs.python_files_any_changed == 'true') && (steps.detect-changed-files.outputs.pyproject_toml_any_changed == 'false') && !cancelled()
+      run: |
+        echo "No changes in pyproject.toml but there are changes in python files. Please update the version in pyproject.toml if the code changes. Otherwise the automatic update of the carlos device may fail."
+        exit 1
