Update monorepo boilerplate

diff --git a/.github/workflows/test-lib-py_carlos_database.yml b/.github/workflows/test-lib-py_carlos_database.yml
--- a/.github/workflows/test-lib-py_carlos_database.yml
+++ b/.github/workflows/test-lib-py_carlos_database.yml
@@ -18,6 +18,7 @@ on:
       - .github/workflows/test-lib-py_carlos_database.yml
       - lib/py_carlos_database/**
       - lib/py_dev_dependencies/**
+      - lib/py_edge_interface/**
 
 
   workflow_dispatch:
@@ -94,7 +95,7 @@ jobs:
       uses: actions/cache@v4
       with:
         path: ./lib/py_carlos_database/.venv
-        key: py_carlos_database-${{ hashFiles('./lib/py_carlos_database/poetry.lock', './lib/py_dev_dependencies/**/*.py', './lib/py_dev_dependencies/**/*.sql', './lib/py_dev_dependencies/poetry.lock')}}-3.11-1.7.1
+        key: py_carlos_database-${{ hashFiles('./lib/py_carlos_database/poetry.lock', './lib/py_dev_dependencies/**/*.py', './lib/py_edge_interface/**/*.py', './lib/py_dev_dependencies/**/*.sql', './lib/py_edge_interface/**/*.sql', './lib/py_dev_dependencies/poetry.lock', './lib/py_edge_interface/poetry.lock')}}-3.11-1.7.1
 
     # Install dependencies. `--no-root` means "install all dependencies but not the project
     # itself", which is what you want to avoid caching _your_ code. The `if` statement
@@ -147,3 +148,20 @@ jobs:
         message: "update lib/py_carlos_database"
         coauthor_email: ${{ github.event.pull_request.user.login }}@users.noreply.github.com
         coauthor_name: ${{ github.event.pull_request.user.login }}
+
+    - name: Set up - Get changed files for CHANGELOG.md
+      if: ${{ !cancelled() }}
+      id: detect-changed-files
+      uses: tj-actions/changed-files@v42
+      with:
+        files_yaml: |
+          pyproject_toml:
+            - lib/py_carlos_database/CHANGELOG.md
+          python_files:
+            - lib/py_carlos_database/carlos/**/*.py
+    - name: Test - Version bump
+      # This step will fail if there are python files changed but the version in pyproject.toml is not updated
+      if: (steps.detect-changed-files.outputs.python_files == 'true') && (steps.detect-changed-files.outputs.pyproject_toml == 'false') && !cancelled()
+      run: |
+        echo "No changes in pyproject.toml but there are changes in python files. Please update the version in pyproject.toml if the code changes. Otherwise the automatic update of the carlos device may fail."
+        exit 1
diff --git a/.github/workflows/test-lib-py_edge_server.yml b/.github/workflows/test-lib-py_edge_server.yml
--- a/.github/workflows/test-lib-py_edge_server.yml
+++ b/.github/workflows/test-lib-py_edge_server.yml
@@ -18,6 +18,7 @@ on:
       - .github/workflows/test-lib-py_edge_server.yml
       - lib/py_edge_server/**
       - lib/py_edge_interface/**
+      - lib/py_carlos_database/**
       - lib/py_dev_dependencies/**
       - lib/py_edge_device/**
 
@@ -96,7 +97,7 @@ jobs:
       uses: actions/cache@v4
       with:
         path: ./lib/py_edge_server/.venv
-        key: py_edge_server-${{ hashFiles('./lib/py_edge_server/poetry.lock', './lib/py_edge_interface/**/*.py', './lib/py_dev_dependencies/**/*.py', './lib/py_edge_device/**/*.py', './lib/py_edge_interface/**/*.sql', './lib/py_dev_dependencies/**/*.sql', './lib/py_edge_device/**/*.sql', './lib/py_edge_interface/poetry.lock', './lib/py_dev_dependencies/poetry.lock', './lib/py_edge_device/poetry.lock')}}-3.11-1.7.1
+        key: py_edge_server-${{ hashFiles('./lib/py_edge_server/poetry.lock', './lib/py_edge_interface/**/*.py', './lib/py_carlos_database/**/*.py', './lib/py_dev_dependencies/**/*.py', './lib/py_edge_device/**/*.py', './lib/py_edge_interface/**/*.sql', './lib/py_carlos_database/**/*.sql', './lib/py_dev_dependencies/**/*.sql', './lib/py_edge_device/**/*.sql', './lib/py_edge_interface/poetry.lock', './lib/py_carlos_database/poetry.lock', './lib/py_dev_dependencies/poetry.lock', './lib/py_edge_device/poetry.lock')}}-3.11-1.7.1
 
     # Install dependencies. `--no-root` means "install all dependencies but not the project
     # itself", which is what you want to avoid caching _your_ code. The `if` statement
@@ -149,3 +150,20 @@ jobs:
         message: "update lib/py_edge_server"
         coauthor_email: ${{ github.event.pull_request.user.login }}@users.noreply.github.com
         coauthor_name: ${{ github.event.pull_request.user.login }}
+
+    - name: Set up - Get changed files for CHANGELOG.md
+      if: ${{ !cancelled() }}
+      id: detect-changed-files
+      uses: tj-actions/changed-files@v42
+      with:
+        files_yaml: |
+          pyproject_toml:
+            - lib/py_edge_server/CHANGELOG.md
+          python_files:
+            - lib/py_edge_server/carlos/**/*.py
+    - name: Test - Version bump
+      # This step will fail if there are python files changed but the version in pyproject.toml is not updated
+      if: (steps.detect-changed-files.outputs.python_files == 'true') && (steps.detect-changed-files.outputs.pyproject_toml == 'false') && !cancelled()
+      run: |
+        echo "No changes in pyproject.toml but there are changes in python files. Please update the version in pyproject.toml if the code changes. Otherwise the automatic update of the carlos device may fail."
+        exit 1
diff --git a/.github/workflows/test-lib-py_monorepo_manager.yml b/.github/workflows/test-lib-py_monorepo_manager.yml
--- a/.github/workflows/test-lib-py_monorepo_manager.yml
+++ b/.github/workflows/test-lib-py_monorepo_manager.yml
@@ -147,3 +147,20 @@ jobs:
         message: "update lib/py_monorepo_manager"
         coauthor_email: ${{ github.event.pull_request.user.login }}@users.noreply.github.com
         coauthor_name: ${{ github.event.pull_request.user.login }}
+
+    - name: Set up - Get changed files for CHANGELOG.md
+      if: ${{ !cancelled() }}
+      id: detect-changed-files
+      uses: tj-actions/changed-files@v42
+      with:
+        files_yaml: |
+          pyproject_toml:
+            - lib/py_monorepo_manager/CHANGELOG.md
+          python_files:
+            - lib/py_monorepo_manager/monorepo_manager/**/*.py
+    - name: Test - Version bump
+      # This step will fail if there are python files changed but the version in pyproject.toml is not updated
+      if: (steps.detect-changed-files.outputs.python_files == 'true') && (steps.detect-changed-files.outputs.pyproject_toml == 'false') && !cancelled()
+      run: |
+        echo "No changes in pyproject.toml but there are changes in python files. Please update the version in pyproject.toml if the code changes. Otherwise the automatic update of the carlos device may fail."
+        exit 1
diff --git a/.github/workflows/test-services-device.yml b/.github/workflows/test-services-device.yml
--- a/.github/workflows/test-services-device.yml
+++ b/.github/workflows/test-services-device.yml
@@ -148,3 +148,20 @@ jobs:
         message: "update services/device"
         coauthor_email: ${{ github.event.pull_request.user.login }}@users.noreply.github.com
         coauthor_name: ${{ github.event.pull_request.user.login }}
+
+    - name: Set up - Get changed files for CHANGELOG.md
+      if: ${{ !cancelled() }}
+      id: detect-changed-files
+      uses: tj-actions/changed-files@v42
+      with:
+        files_yaml: |
+          pyproject_toml:
+            - services/device/CHANGELOG.md
+          python_files:
+            - services/device/device/**/*.py
+    - name: Test - Version bump
+      # This step will fail if there are python files changed but the version in pyproject.toml is not updated
+      if: (steps.detect-changed-files.outputs.python_files == 'true') && (steps.detect-changed-files.outputs.pyproject_toml == 'false') && !cancelled()
+      run: |
+        echo "No changes in pyproject.toml but there are changes in python files. Please update the version in pyproject.toml if the code changes. Otherwise the automatic update of the carlos device may fail."
+        exit 1
